# Generated by Django 3.2 on 2021-04-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_rename_status_campaigns_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
